-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2025-05-08 22:19:57 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g



DROP TABLE DIM_MC_BAIRRO CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_CATEGORIA_PROD CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_CENTRO_DISTRIBUICAO CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_CIDADE CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_CLIENTE CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_ESTADO CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_FORMA_PAGTO CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_FUNCIONARIO CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_ORIGEM_VDA CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_PEDIDO_VENDA CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_PRODUTO CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_REGIAO CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_STATUS_VENDA CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_SUB_CATEGORIA_PROD CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_TEMPO CASCADE CONSTRAINTS 
;

DROP TABLE DIM_MC_TIPO_VENDA CASCADE CONSTRAINTS 
;

DROP TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD CASCADE CONSTRAINTS 
;

