-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2025-05-08 22:22:19 BRT
--   site:      SQL Server 2012
--   tipo:      SQL Server 2012



ALTER TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD 
    DROP CONSTRAINT FK_MC_DIM_BAIRRO_CLI_PSC 
GO

DROP TABLE DIM_MC_BAIRRO
GO

ALTER TABLE DIM_MC_SUB_CATEGORIA_PROD 
    DROP CONSTRAINT FK_MC_DIM_SUBCATEG_CATEG 
GO

DROP TABLE DIM_MC_CATEGORIA_PROD
GO

ALTER TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD 
    DROP CONSTRAINT FK_MC_DIM_CD_PESQ_SATISF 
GO

DROP TABLE DIM_MC_CENTRO_DISTRIBUICAO
GO

ALTER TABLE DIM_MC_BAIRRO 
    DROP CONSTRAINT FK_MC_DIM_CIDADE_BAIRRO 
GO

DROP TABLE DIM_MC_CIDADE
GO

ALTER TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD 
    DROP CONSTRAINT PK_MC_DIM_CLIENTE_PESQ_SATISF 
GO

DROP TABLE DIM_MC_CLIENTE
GO

ALTER TABLE DIM_MC_CIDADE 
    DROP CONSTRAINT FK_MC_DIM_ESTADO_CIDADE 
GO

DROP TABLE DIM_MC_ESTADO
GO

ALTER TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD 
    DROP CONSTRAINT FK_MC_DIM_FORMPAGTO_PESQSATISF 
GO

DROP TABLE DIM_MC_FORMA_PAGTO
GO

ALTER TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD 
    DROP CONSTRAINT FK_MC_DIM_FUNC_PESQ_SATISF 
GO

DROP TABLE DIM_MC_FUNCIONARIO
GO

ALTER TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD 
    DROP CONSTRAINT FK_MC_DIM_ORIG_VDA_PESQSATISF 
GO

DROP TABLE DIM_MC_ORIGEM_VDA
GO

ALTER TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD 
    DROP CONSTRAINT FK_MC_DIM_PEDVDA_PESQSATISF 
GO

DROP TABLE DIM_MC_PEDIDO_VENDA
GO

ALTER TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD 
    DROP CONSTRAINT FK_MC_DIM_PROD_PESQ_SATISF 
GO

DROP TABLE DIM_MC_PRODUTO
GO

ALTER TABLE DIM_MC_ESTADO 
    DROP CONSTRAINT FK_MC_DIM_REGIAO_BAIRRO 
GO

DROP TABLE DIM_MC_REGIAO
GO

ALTER TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD 
    DROP CONSTRAINT FK_MC_DIM_STAT_VDA_PESQSATISF 
GO

DROP TABLE DIM_MC_STATUS_VENDA
GO

ALTER TABLE DIM_MC_PRODUTO 
    DROP CONSTRAINT FK_MC_DIM_CATEG_PROD 
GO

DROP TABLE DIM_MC_SUB_CATEGORIA_PROD
GO

ALTER TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD 
    DROP CONSTRAINT FK_MC_DIM_TEMPO_DT_PEDIDO 
GO

DROP TABLE DIM_MC_TEMPO
GO

ALTER TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD 
    DROP CONSTRAINT FK_MC_DIM_TIP_VDA_PESQSATISF 
GO

DROP TABLE DIM_MC_TIPO_VENDA
GO

DROP TABLE FTO_ENTREGA_PRD_PESQ_SATISF_CD
GO
